"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { requestAnalysis, requestPlan } from "./client";
import { p5EvaluationFixtures } from "./evaluationFixtures";
import type { AnalysisResult, PlanningResult } from "./types";
import styles from "./evaluation.module.css";

type Row = { sourceId: string; profile: "fast" | "quality"; analysis: AnalysisResult; planner?: PlanningResult };
export function EvaluationLab() {
  const [profile, setProfile] = useState<"quick" | "full">("quick"); const [rows, setRows] = useState<Row[]>([]); const [running, setRunning] = useState(false); const [progress, setProgress] = useState(0);
  const controller = useRef<AbortController | null>(null); const [error, setError] = useState("");
  useEffect(() => () => controller.current?.abort(), []);
  const fixtures = profile === "quick" ? p5EvaluationFixtures.slice(0, 2) : p5EvaluationFixtures; const metrics = useMemo(() => !rows.length ? null : ({ schema: Math.round(rows.filter((row) => row.analysis.rawMetrics.schemaValid).length / rows.length * 100), citations: Math.round(rows.filter((row) => row.analysis.rawMetrics.semanticValid).length / rows.length * 100), failures: Math.round(rows.filter((row) => row.analysis.status === "failed").length / rows.length * 100), latency: Math.round(rows.reduce((sum, row) => sum + row.analysis.latencyMs, 0) / rows.length) }), [rows]);
  async function run() { setRunning(true); setRows([]); setProgress(0); setError(""); const operation = new AbortController(); controller.current = operation; const next: Row[] = []; const total = fixtures.length; try { for (const fixture of fixtures) for (const modelProfile of ["fast"] as const) { const analysis = await requestAnalysis(fixture.source.id, modelProfile, operation.signal); const row: Row = { sourceId: fixture.source.id, profile: modelProfile, analysis }; if (profile === "full") row.planner = await requestPlan(fixture.goldSpec, modelProfile, operation.signal); next.push(row); setRows([...next]); setProgress(next.length / total); } } catch (caught) { setError(operation.signal.aborted ? "Evaluation stopped." : caught instanceof Error ? caught.message : "Evaluation failed."); } finally { controller.current = null; setRunning(false); } }
  return <div className={styles.shell}><header><div><span>PROTOTYPE 5 · EVALUATION</span><h1>Source grounding before speed.</h1></div><nav><a href="/prototype-5">← Prototype 5</a><select value={profile} disabled={running} onChange={(event) => setProfile(event.target.value as "quick" | "full")}><option value="quick">Quick · 2 sources</option><option value="full">Full · 5 sources + planners</option></select><button disabled={running} onClick={() => void run()}>{running ? "Running sequentially…" : "Run evaluation"}</button>{running ? <button onClick={() => controller.current?.abort()}>Stop evaluation</button> : null}</nav></header><div className={styles.progress}><i style={{width:`${progress*100}%`}}/></div><main>{error ? <p role="alert">{error}</p> : null}<section className={styles.metrics}>{[["Validated schema",metrics?.schema,"target ≥90%"],["Citation valid",metrics?.citations,"invalid entering review: 0"],["Explicit failures",metrics?.failures,"reported, never hidden"],["Mean latency",metrics?`${metrics.latency} ms`:undefined,"CPU-only background stage"]].map(([label,value,note])=><article key={String(label)}><span>{label}</span><strong>{value===undefined?"—":typeof value==="number"?`${value}%`:value}</strong><small>{note}</small></article>)}</section><section className={styles.results}><header><span>Source</span><span>Model</span><span>Analysis</span><span>Planner</span><span>Latency</span></header>{rows.map((row)=><div key={`${row.sourceId}-${row.profile}`}><strong>{row.sourceId}</strong><span>{row.analysis.modelId}</span><span data-ok={row.analysis.status==="accepted"}>{row.analysis.status}</span><span>{row.planner?.status??"not run"}</span><span>{(row.analysis.latencyMs/1000).toFixed(1)} s</span></div>)}</section></main></div>;
}
