"use client";

import { useMemo, useState } from "react";
import { getSourceDocument } from "./sources";
import type { ApprovedLearningSpec, BlockOutcome, CompiledBlock, CompiledLessonManifest } from "./types";
import styles from "./prototype5.module.css";

type Props = { block: CompiledBlock; manifest: CompiledLessonManifest; selectedRowId: string; revealedRows: string[]; onRow: (id: string) => void; onReveal: (id: string) => void; onComplete: (outcome: BlockOutcome) => void };
const outcome = (block: CompiledBlock, result: BlockOutcome["result"], attempts = 1, misconceptionIds: string[] = []): BlockOutcome => ({ blockId: block.id, result, attempts, hintUsed: false, misconceptionIds });

function relationshipText(spec: Pick<ApprovedLearningSpec, "concepts" | "relationships">, block: CompiledBlock) { const relation = spec.relationships.find((item) => item.id === block.relationshipIds[0]); if (!relation) return spec.concepts.slice(0, 2).map((item) => item.name).join(" and "); const from = spec.concepts.find((item) => item.id === relation.fromConceptId)?.name ?? relation.fromConceptId; const to = spec.concepts.find((item) => item.id === relation.toConceptId)?.name ?? relation.toConceptId; return `${from} ${relation.type} ${to}`; }

export function P5Primitive({ block, manifest, selectedRowId, revealedRows, onRow, onReveal, onComplete }: Props) {
  const source = getSourceDocument(manifest.sourceDocumentId)!; const table = source.tables.find((item) => "tableId" in block.render && item.id === block.render.tableId) ?? source.tables[0];
  const [choice, setChoice] = useState(""); const [attempts, setAttempts] = useState(0); const [revealed, setRevealed] = useState(false); const [ordered, setOrdered] = useState<string[]>([]);
  const selectedRow = table?.rows.find((row) => row.id === selectedRowId) ?? table?.rows[0];
  const predictionCorrect = useMemo(() => { const relation = manifest.relationships.find((item) => item.id === block.relationshipIds[0]); return relation?.type === "decreases" ? "decreases" : "increases"; }, [manifest, block.relationshipIds]);
  if (block.render.kind === "prediction") return <div className={styles.actionContent}><span>START WITH EVIDENCE</span><h2>{block.title}</h2><p>{block.prompt}</p><strong className={styles.objectQuestion}>As the input increases, what happens to the related outcome?</strong><div className={styles.choiceRow}>{["increases","decreases","stays-same"].map((id) => <button className={choice === id ? styles.selected : ""} type="button" key={id} onClick={() => setChoice(id)}>{id.replace("-", " ")}</button>)}</div><button className={styles.primary} disabled={!choice} onClick={() => { const next = attempts + 1; setAttempts(next); const correct = choice === predictionCorrect; onComplete(outcome(block, correct ? "correct" : "incorrect", next, correct ? [] : block.possibleMisconceptionIds.slice(0, 1))); }}>Commit prediction →</button><small>Relationship: {relationshipText(manifest, block)}</small></div>;
  if (block.render.kind === "parameter-experiment") { const config = block.render; return <div className={styles.actionContent}><span>DISCRETE SOURCE EXPERIMENT</span><h2>{block.title}</h2><p>{block.prompt}</p><div className={styles.trialButtons}>{table.rows.map((row) => <button className={selectedRowId === row.id ? styles.selected : ""} type="button" key={row.id} onClick={() => { onRow(row.id); onReveal(row.id); }}>{row.values[config.inputColumnId]} {table.columns.find((column) => column.id === config.inputColumnId)?.unit}</button>)}</div>{selectedRow ? <div className={styles.measureReadout}><span>TRUSTED RESULT</span><strong>{selectedRow.values[config.outputColumnId]} {table.columns.find((column) => column.id === config.outputColumnId)?.unit}</strong></div> : null}<button className={styles.primary} disabled={revealedRows.length < 2} onClick={() => onComplete(outcome(block, "completed"))}>Keep these observations →</button></div>; }
  if (block.render.kind === "comparison") { const rows = block.render.rowIds.map((id) => table.rows.find((row) => row.id === id)).filter(Boolean); return <div className={styles.actionContent}><span>COMPARE TRUSTED TRIALS</span><h2>{block.title}</h2><p>{block.prompt}</p><div className={styles.compareRows}>{rows.map((row) => <article key={row!.id}>{block.render.kind === "comparison" ? block.render.columnIds.map((columnId) => <b key={columnId}>{row!.values[columnId]} <small>{table.columns.find((column) => column.id === columnId)?.unit}</small></b>) : null}</article>)}</div><button className={styles.primary} onClick={() => onComplete(outcome(block, "completed"))}>Use this comparison →</button></div>; }
  if (block.render.kind === "data-plot") { const config = block.render; return <div className={styles.actionContent}><span>GENERATE THE GRAPH</span><h2>{block.title}</h2><p>{block.prompt}</p><div className={styles.revealButtons}>{table.rows.map((row) => <button className={revealedRows.includes(row.id) ? styles.selected : ""} key={row.id} type="button" onClick={() => { onRow(row.id); onReveal(row.id); }}>{row.values[config.xColumnId]}</button>)}</div><button className={styles.primary} disabled={revealedRows.length < table.rows.length} onClick={() => onComplete(outcome(block, "completed"))}>Use the completed pattern →</button></div>; }
  if (block.render.kind === "evidence-reveal") return <div className={styles.actionContent}><span>EVIDENCE BECOMES A RULE</span><h2>{block.title}</h2><p>{block.prompt}</p>{revealed ? <div className={styles.factReveal}>{block.render.factIds.map((id) => <strong key={id}>{manifest.facts.find((fact) => fact.id === id)?.statement}</strong>)}</div> : <button className={styles.revealAction} type="button" onClick={() => setRevealed(true)}>Reveal only approved facts</button>}<button className={styles.primary} disabled={!revealed} onClick={() => onComplete(outcome(block, "completed"))}>Carry the rule forward →</button></div>;
  if (block.render.kind === "target-challenge") { const config = block.render; const held = table.rows.find((row) => row.id === config.heldOutRowId)!; const values = [...new Set(table.rows.map((row) => String(row.values[config.predictionColumnId])))]; return <div className={styles.actionContent}><span>HELD-OUT APPLICATION</span><h2>{block.title}</h2><p>{block.prompt}</p><div className={styles.heldOut}><span>Condition</span>{table.columns.filter((column) => column.id !== config.predictionColumnId).map((column) => <strong key={column.id}>{held.values[column.id]} {column.unit}</strong>)}</div><div className={styles.choiceRow}>{values.map((value) => <button className={choice === value ? styles.selected : ""} key={value} type="button" onClick={() => setChoice(value)}>{value} {table.columns.find((column) => column.id === config.predictionColumnId)?.unit}</button>)}</div><button className={styles.primary} disabled={!choice} onClick={() => { const next = attempts + 1; setAttempts(next); if (choice === String(held.values[config.predictionColumnId])) onComplete(outcome(block, "correct", next)); }}>Test against trusted row →</button></div>; }
  if (block.render.kind === "step-sequence") { const items = block.render.relationshipIds; return <div className={styles.actionContent}><span>ORDER APPROVED RELATIONSHIPS</span><h2>{block.title}</h2><p>{block.prompt}</p>{items.map((id) => <button className={ordered.includes(id) ? styles.selected : ""} type="button" key={id} disabled={ordered.includes(id)} onClick={() => setOrdered((current) => [...current, id])}>{ordered.indexOf(id) >= 0 ? ordered.indexOf(id) + 1 : "·"} {id}</button>)}<button className={styles.primary} disabled={ordered.length < items.length} onClick={() => onComplete(outcome(block, "completed"))}>Keep sequence →</button></div>; }
  return <div className={styles.actionContent}><span>APPROVED REPRESENTATION</span><h2>{block.title}</h2><p>{block.prompt}</p><button className={styles.primary} onClick={() => onComplete(outcome(block, "completed"))}>Use this evidence →</button></div>;
}
