import type { LearningBlock } from "./domain";
import { MORE_RESISTANCE_MORE_CURRENT, OBJECTIVES } from "./curriculum";

export const adaptiveBlockCatalog: LearningBlock[] = [
  {
    id: "complete-circuit-foundation",
    title: "Make the circuit work",
    objectiveIds: [OBJECTIVES.circuit],
    prerequisiteObjectiveIds: [],
    difficulty: 1,
    purpose: "introduce",
    selectionRole: "core",
    interactionType: "open-close-switch",
    modality: ["interactive", "visual"],
    misconceptionsAddressed: [],
    estimatedMinutes: 1,
    priority: 100,
    sourceFactIds: ["fact-closed-path"],
    content: { kind: "complete-circuit", voltage: 9 },
  },
  {
    id: "battery-voltage-discovery",
    title: "Find what makes charge move",
    objectiveIds: [OBJECTIVES.voltage],
    prerequisiteObjectiveIds: [OBJECTIVES.circuit],
    difficulty: 1,
    purpose: "introduce",
    selectionRole: "core",
    interactionType: "remove-restore-source",
    modality: ["interactive", "visual", "comparison"],
    misconceptionsAddressed: [],
    estimatedMinutes: 1,
    priority: 100,
    sourceFactIds: ["fact-voltage-push", "fact-current-flow"],
    content: { kind: "voltage-discovery", voltage: 9 },
  },
  {
    id: "resistance-prediction-experiment",
    title: "Predict, then test resistance",
    objectiveIds: [OBJECTIVES.resistance],
    prerequisiteObjectiveIds: [OBJECTIVES.circuit, OBJECTIVES.voltage],
    difficulty: 1,
    purpose: "check",
    selectionRole: "core",
    interactionType: "prediction-and-slider",
    modality: ["interactive", "visual", "numerical"],
    misconceptionsAddressed: [MORE_RESISTANCE_MORE_CURRENT],
    estimatedMinutes: 2,
    priority: 100,
    sourceFactIds: ["fact-resistance-opposes", "fact-fixed-voltage-relationship"],
    content: {
      kind: "resistance-diagnostic",
      voltage: 9,
      initialResistance: 4,
      targetResistance: 8,
    },
  },
  {
    id: "resistance-misconception-visual",
    title: "See why current falls",
    objectiveIds: [OBJECTIVES.resistance],
    prerequisiteObjectiveIds: [OBJECTIVES.voltage],
    difficulty: 1,
    purpose: "remediate",
    selectionRole: "remediation",
    interactionType: "cause-and-effect-visual",
    modality: ["visual", "analogy", "text"],
    misconceptionsAddressed: [MORE_RESISTANCE_MORE_CURRENT],
    estimatedMinutes: 1,
    priority: 95,
    sourceFactIds: ["fact-resistance-opposes", "fact-fixed-voltage-relationship"],
    content: { kind: "misconception-visual" },
  },
  {
    id: "guided-resistance-experiment",
    title: "Compare three resistors",
    objectiveIds: [OBJECTIVES.resistance],
    prerequisiteObjectiveIds: [OBJECTIVES.voltage],
    difficulty: 1,
    purpose: "explore",
    selectionRole: "guided-practice",
    interactionType: "guided-value-comparison",
    modality: ["interactive", "visual", "numerical"],
    misconceptionsAddressed: [MORE_RESISTANCE_MORE_CURRENT],
    estimatedMinutes: 2,
    priority: 90,
    sourceFactIds: ["fact-fixed-voltage-relationship", "fact-ohms-law"],
    content: {
      kind: "guided-resistance",
      voltage: 9,
      resistanceValues: [3, 6, 9],
    },
  },
  {
    id: "resistance-equivalent-retry",
    title: "Try the idea again",
    objectiveIds: [OBJECTIVES.resistance],
    prerequisiteObjectiveIds: [OBJECTIVES.voltage],
    difficulty: 1,
    purpose: "check",
    selectionRole: "retry",
    interactionType: "equivalent-multiple-choice",
    modality: ["prediction", "text"],
    misconceptionsAddressed: [MORE_RESISTANCE_MORE_CURRENT],
    estimatedMinutes: 1,
    priority: 85,
    sourceFactIds: ["fact-fixed-voltage-relationship"],
    content: {
      kind: "equivalent-retry",
      voltage: 9,
      firstResistance: 3,
      secondResistance: 9,
    },
  },
  {
    id: "current-resistance-graph",
    title: "See the pattern as a graph",
    objectiveIds: [OBJECTIVES.graph],
    prerequisiteObjectiveIds: [OBJECTIVES.resistance],
    difficulty: 2,
    purpose: "apply",
    selectionRole: "core",
    interactionType: "graph-inspection",
    modality: ["visual", "numerical"],
    misconceptionsAddressed: [MORE_RESISTANCE_MORE_CURRENT],
    estimatedMinutes: 1,
    priority: 100,
    sourceFactIds: ["fact-fixed-voltage-relationship", "fact-ohms-law"],
    content: {
      kind: "relationship-graph",
      voltage: 9,
      resistanceValues: [2, 3, 4, 6, 9, 12, 18],
    },
  },
  {
    id: "target-current-challenge",
    title: "Choose a resistor for the target",
    objectiveIds: [OBJECTIVES.target],
    prerequisiteObjectiveIds: [OBJECTIVES.graph],
    difficulty: 2,
    purpose: "apply",
    selectionRole: "core",
    interactionType: "single-choice-design",
    modality: ["problem-solving", "numerical"],
    misconceptionsAddressed: [],
    estimatedMinutes: 1,
    priority: 100,
    sourceFactIds: ["fact-ohms-law", "fact-worked-example"],
    content: {
      kind: "target-current",
      voltage: 9,
      targetCurrent: 1.5,
      resistanceOptions: [3, 6, 9, 12],
    },
  },
  {
    id: "final-circuit-design-challenge",
    title: "Design one final circuit",
    objectiveIds: [OBJECTIVES.design],
    prerequisiteObjectiveIds: [OBJECTIVES.target],
    difficulty: 3,
    purpose: "apply",
    selectionRole: "core",
    interactionType: "transfer-design",
    modality: ["problem-solving", "visual", "numerical"],
    misconceptionsAddressed: [],
    estimatedMinutes: 2,
    priority: 100,
    sourceFactIds: ["fact-ohms-law", "fact-fixed-voltage-relationship"],
    content: {
      kind: "circuit-design",
      voltage: 12,
      targetCurrent: 2,
      resistanceOptions: [2, 4, 6, 12],
    },
  },
];

export const adaptiveBlockCatalogById = new Map(
  adaptiveBlockCatalog.map((block) => [block.id, block]),
);
