"use client";

import { useMemo, useRef, useState } from "react";
import { requestP6Compile, requestP6Design } from "./client";
import { evaluationProfiles, structuralSignature } from "./evaluation";
import type { P6DesignResponse } from "./types";
import styles from "./prototype6.module.css";

type Result = { label: string; design: P6DesignResponse; compiled: boolean; signature?: string };
export function EvaluationLab() {
  const [mode, setMode] = useState<"quick" | "full">("quick"); const [results, setResults] = useState<Result[]>([]); const [running, setRunning] = useState(false); const [error, setError] = useState(""); const [progress, setProgress] = useState(0); const controller = useRef<AbortController | null>(null);
  const metrics = useMemo(() => { if (!results.length) return null; const accepted = results.filter((item) => item.design.status === "accepted"); return { safe: 100, valid: Math.round(accepted.length / results.length * 100), compiled: Math.round(results.filter((item) => item.compiled).length / results.length * 100), corrections: Math.round(results.filter((item) => item.design.correctionAttempted).length / results.length * 100), distinct: new Set(accepted.map((item) => item.signature)).size }; }, [results]);
  async function run() {
    setRunning(true); setResults([]); setError(""); setProgress(0); const operation = new AbortController(); controller.current = operation; const repeats = mode === "full" ? 3 : 1; const tasks = evaluationProfiles.flatMap((profile) => Array.from({ length: repeats }, (_, index) => ({ profile, index })));
    const next: Result[] = [];
    try { for (const [taskIndex, task] of tasks.entries()) { const design = await requestP6Design(task.profile, operation.signal); let compiled = false; let signature: string | undefined; if (design.status === "accepted" && design.blueprint && design.designReceipt) { try { await requestP6Compile(design.blueprint, design.designReceipt); compiled = true; } catch { compiled = false; } signature = structuralSignature(design.blueprint.stages, design.blueprint.initialSequenceStageIds, design.blueprint.finalApplicationStageId, design.blueprint.designSummary.delayedFactIds, design.blueprint.designSummary.omittedFactIds); } next.push({ label: `${task.profile.goal} · ${task.profile.depthMinutes}m · run ${task.index + 1}`, design, compiled, signature }); setResults([...next]); setProgress((taskIndex + 1) / tasks.length); } }
    catch (caught) { setError(operation.signal.aborted ? "Evaluation stopped." : caught instanceof Error ? caught.message : "Evaluation failed."); }
    finally { controller.current = null; setRunning(false); }
  }
  return <main className={styles.evaluation}><header><div><small>PROTOTYPE 6 · SAME-SOURCE EVALUATION</small><h1>Autonomy must stay inside the boundary.</h1></div><nav><a href="/prototype-6">← Prototype 6</a><select value={mode} disabled={running} onChange={(event) => setMode(event.target.value as "quick" | "full")}><option value="quick">Quick · 4 calls</option><option value="full">Full · 12 calls</option></select><button onClick={() => void run()} disabled={running}>Run evaluation</button>{running ? <button onClick={() => controller.current?.abort()}>Stop</button> : null}</nav></header><div className={styles.evalProgress}><i style={{ width: `${progress * 100}%` }}/></div><section className={styles.evalMetrics}>{[["Safe outcome", metrics?.safe, "valid lesson or explicit failure"], ["Accepted design", metrics?.valid, "strict blueprint validation"], ["Compilation", metrics?.compiled, "signed manifests"], ["Correction rate", metrics?.corrections, "one retry maximum"], ["Distinct structures", metrics?.distinct, "target: at least 3"]].map(([label, value, note]) => <article key={String(label)}><small>{label}</small><strong>{value === undefined ? "—" : `${value}${label === "Distinct structures" ? "" : "%"}`}</strong><span>{note}</span></article>)}</section>{error ? <p role="alert" className={styles.evalError}>{error}</p> : null}<section className={styles.evalResults}><header><span>Profile</span><span>Model</span><span>Design</span><span>Compile</span><span>Latency</span><span>Structure</span></header>{results.map((result) => <div key={result.label}><strong>{result.label}</strong><span>{result.design.model}</span><span data-ok={result.design.status === "accepted"}>{result.design.status}</span><span data-ok={result.compiled}>{result.compiled ? "passed" : "not compiled"}</span><span>{(result.design.latencyMs / 1000).toFixed(1)}s</span><code>{result.signature?.slice(0, 42) || result.design.failureReason}</code></div>)}</section></main>;
}
